# Pandas - Analyzing DataFrames


## Viewing the Data
One of the most used method for getting a quick overview of the DataFrame, is the head() method.

The head() method returns the headers and a specified number of rows, starting from the top.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('dataW3S.csv')

print(df.head(10)) # As primeiras 10 linhas

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


In [4]:
print(df.head())  # As primeiras 5 linhas (padrão)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [5]:
# Também existe o método tail() para ver as últimas linhas do DataFrame

print(df.tail())  # As últimas 5 linhas (padrão)

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


# Info About the Data

The DataFrames object has a method called info(), that gives you more information about the data set.

In [7]:
print(df.info())  # Informações sobre o DataFrame

'''
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None
'''

# Nos fala que existem 169 linhas e 4 colunas
'''
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
'''

# Nome de cada coluna e seu tipo de dado
'''
#      Column    Non-Null Count  Dtype  
  ---  ------    --------------  -----  
   0   Duration  169 non-null    int64  
   1   Pulse     169 non-null    int64  
   2   Maxpulse  169 non-null    int64  
   3   Calories  164 non-null    float64
'''

# resumo dos tipos de dados e uso de memória
'''
  dtypes: float64(1), int64(3)
  memory usage: 5.4 KB
'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None


'\n  dtypes: float64(1), int64(3)\n  memory usage: 5.4 KB\n'

## Null Values

O método .info() também nos fala quando valores não nulos (Non-Null Values) existem em cada coluna, e no df usado aparenta tem 164 de 169 valores não nulos na coluna "calories".

O que significa que existem 5 linhas sem nenhum valor nessa coluna.

Valores nulos e informações faltando em linhas podem ser ruins para analisar dados e devemos levar em consideração remover as linhas com Null Values.